# Generated by Django 5.1.3 on 2024-12-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Адрес электронной почты уже используется.'}, max_length=254, null=True, verbose_name='Адрес электронной почты.'),
        ),
    ]
